import { load } from "cheerio";

const response = await (
  await fetch("https://www.cloudflarestatus.com/locations")
).text();
const $ = load(response);
const locations = Object.fromEntries(
  $(".flex.items-center.gap-3.bg-kumo-base.px-4.py-3")
    .toArray()
    .map((el) => {
      const spans = $(
        ".flex.min-w-0.flex-1.items-baseline.gap-2 > span",
        el,
      ).toArray();
      if (spans.length !== 2) {
        return undefined;
      }
      const [loc, abbr] = spans;
      return [$(abbr).text().trim(), $(loc).text().trim()];
    })
    .filter((x) => x !== undefined),
);

console.log(
  `// This file is auto-generated by scripts/cloudflare-colo-update.ts
// run "bun colo > ./content/site/colo.ts" to update
export const CloudflareServerLocations = ` +
    JSON.stringify(locations, null, 2) +
    ` as const`,
);
